name: 'GHA Test Runner 🧪'
description: 'Run test cases for different languages and frameworks'
author: 'Jaynath Ray'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'shield'  
  color: 'green'
